version: '3.4'
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - ./work:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
